---
- when: inventory_hostname in groups['webitel_engine']
  block:
    - include_tasks: install.yml
      tags:
        - webitel_engine_install

    - include_tasks: configure.yml
      tags:
        - webitel_engine_configure