---
- name: Ensure bootstrapped file exists
  ansible.builtin.copy:
    content: ""
    dest: /opt/webitel/.bootstrap
    force: false

- name: Read bootstrapped state. Ensure /opt/webitel/.bootstrap contains webitel_messages
  ansible.builtin.lineinfile:
    path: /opt/webitel/.bootstrap
    regexp: ^webitel_messages
    state: absent
  check_mode: true
  changed_when: false
  ignore_errors: true
  register: bootstrap_state

- when: not bootstrap_state.found
  block:
    - name: Copy webitel systemd files
      ansible.builtin.copy:
        src: /opt/webitel/etc/systemd/system/{{ item }}
        dest: /etc/systemd/system/
        remote_src: true
      with_items:
        - messages-bot.service
        - messages-srv.service
      when:
        - ansible_service_mgr == "systemd"

    - name: Change messages-bot chat URL
      ansible.builtin.replace:
        path: /etc/systemd/system/messages-bot.service
        after: --site_url="
        before: /chat"
        regexp: ^(.+)$
        replace: https://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}

    - name: URL for letsencrypt
      ansible.builtin.replace:
        path: /etc/systemd/system/messages-bot.service
        after: --site_url="
        before: /chat"
        regexp: ^(.+)$
        replace: https://{{ nginx_site_name }}
      when: nginx_letsencrypt | bool

    - when: groups['all'] | length > 1
      block:
        - name: Change messages-bot IP
          ansible.builtin.replace:
            path: /etc/systemd/system/messages-bot.service
            after: --address=
            before: :10031
            regexp: ^(.+)$
            replace: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"

    - name: Enable webitel at startup (systemd)
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: true
        daemon_reload: true
        state: restarted
      with_items:
        - messages-bot.service
        - messages-srv.service
      when:
        - ansible_service_mgr == "systemd"

    - name: Insert info into bootstrapped state file
      ansible.builtin.lineinfile:
        path: /opt/webitel/.bootstrap
        line: webitel_messages
        insertbefore: BOF
