---
- when: inventory_hostname in groups['consul']
  block:
    - ansible.builtin.include_tasks: install.yml
      tags:
        - consul_install

    - ansible.builtin.include_tasks: configure.yml
      tags:
        - consul_configure
