---
- when: inventory_hostname in groups['consul']
  block:
    - include_tasks: install.yml
      tags:
        - consul_install

    - include_tasks: configure.yml
      tags:
        - consul_configure