---
- when: inventory_hostname in groups['grafana']
  block:
    - include_tasks: install.yml
      tags:
        - grafana_install
      when:
        - grafana_enable | bool

    - include_tasks: configure.yml
      tags:
        - grafana_configure
      when:
        - grafana_enable | bool

    - include_tasks: datasources.yml
      tags:
        - grafana_datasource
      when:
        - grafana_enable | bool

    - include_tasks: dashboards.yml
      tags:
        - grafana_dashboard
      when:
        - grafana_enable | bool
        - grafana_basic_dashboards | bool
