---
- hosts: all
  become: true
  become_user: root
  any_errors_fatal: true
  pre_tasks:
    - include_tasks: tasks/debian.yml
    - include_tasks: tasks/preflight.yml
    - include_tasks: tasks/setup.yml
  roles:
    - webitel/common
    - consul
    - rabbitmq
    - postgresql/install
    - postgresql/main
    - postgresql/standby
    - grafana
    - nginx/install
    - freeswitch
    - rtpengine
    - opensips
    - webitel/core
    - webitel/storage
    - webitel/engine
    - webitel/call_center
    - webitel/flow_manager
    - webitel/messages
  post_tasks:
    - include_tasks: tasks/finish.yml
