---
# Install a collection from Ansible Galaxy.
collections:
  - name: ansible.utils
    source: https://galaxy.ansible.com

  - name: ansible.posix

  - name: community.general

  - name: community.rabbitmq

  - name: community.postgresql

