---
- name: Get kernel version
  ansible.builtin.command: uname -r
  register: kernel_version

- name: Install rtpengine packages
  ansible.builtin.apt:
    name:
      - libspandsp2
      - ngcp-rtpengine
      - linux-headers-{{ kernel_version.stdout }}
    state: latest
    install_recommends: false
    update_cache: false
