---
- when: inventory_hostname in groups['rtpengine']
  block:
    - ansible.builtin.include_tasks: install.yml
      tags:
        - rtpengine_install

    - ansible.builtin.include_tasks: configure.yml
      tags:
        - rtpengine_configure
