---
- name: Install RTPEngine and sipwise repository
  ansible.builtin.include_tasks:
    file: install.yml
    apply:
      tags: [rtpengine_install]
  tags: [rtpengine_install]

- name: Configure RTPEngine
  ansible.builtin.include_tasks:
    file: configure.yml
    apply:
      tags: [rtpengine_configure]
  tags: [rtpengine_configure]
