---
- when: inventory_hostname in groups['rtpengine']
  block:
    - include_tasks: install.yml
      tags:
        - rtpengine_install

    - include_tasks: configure.yml
      tags:
        - rtpengine_configure