---
- when: inventory_hostname in groups['rtpengine']
  block:
    - include: install.yml
      become: true
      tags:
        - rtpengine_install

    - include: configure.yml
      become: true
      tags:
        - rtpengine_configure