---
- name: Ensure bootstrapped file exists
  copy:
    content: ""
    dest: /opt/webitel/.bootstrap
    force: no

- name: Read bootstrapped state. Ensure /opt/webitel/.bootstrap contains webitel_core
  lineinfile:
    path: /opt/webitel/.bootstrap
    regexp: "^webitel_core"
    state: absent
  check_mode: yes
  changed_when: false
  ignore_errors: true
  register: bootstrap_state

- when: not bootstrap_state.found
  block:
    - name: Copy webitel systemd files
      copy:
        src: '/opt/webitel/etc/systemd/system/{{ item }}'
        dest: /etc/systemd/system/
        remote_src: yes
      with_items:
        - webitel-api.service
        - webitel-app.service
        - webitel-uac.service
      when:
        - ansible_service_mgr == "systemd"

    - when: groups['all'] | length > 1
      block:
        - name: Webitel API service IP
          replace:
            path: '/etc/systemd/system/webitel-api.service'
            after: '--address='
            before: ':8080'
            regexp: '^(.+)$'
            replace: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"

    - name: Enable webitel at startup (systemd)
      systemd:
        name: '{{ item }}'
        enabled: yes
        daemon_reload: yes
        state: restarted
      with_items:
        - webitel-api.service
        - webitel-app.service
        - webitel-uac.service
      when:
        - ansible_service_mgr == "systemd"

    - name: Insert info into bootstrapped state file
      lineinfile:
        path: /opt/webitel/.bootstrap
        line: "webitel_core"
        insertbefore: BOF
