---
- name: Ensure bootstrapped file exists
  ansible.builtin.copy:
    content: ""
    dest: /opt/webitel/.bootstrap
    force: false

- name: Read bootstrapped state. Ensure /opt/webitel/.bootstrap contains webitel_core
  ansible.builtin.lineinfile:
    path: /opt/webitel/.bootstrap
    regexp: ^webitel_core
    state: absent
  check_mode: true
  changed_when: false
  ignore_errors: true
  register: bootstrap_state

- when: not bootstrap_state.found
  block:
    - name: Copy webitel systemd files
      ansible.builtin.copy:
        src: /opt/webitel/etc/systemd/system/{{ item }}
        dest: /etc/systemd/system/
        remote_src: true
      with_items:
        - webitel-api.service
        - webitel-app.service
        - webitel-uac.service
      when:
        - ansible_service_mgr == "systemd"

    - when: groups['all'] | length > 1
      block:
        - name: Webitel API service IP
          ansible.builtin.replace:
            path: /etc/systemd/system/webitel-api.service
            after: --address=
            before: :8080
            regexp: ^(.+)$
            replace: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"

    - name: Enable webitel at startup (systemd)
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: true
        daemon_reload: true
        state: restarted
      with_items:
        - webitel-api.service
        - webitel-app.service
        - webitel-uac.service
      when:
        - ansible_service_mgr == "systemd"

    - name: Insert info into bootstrapped state file
      ansible.builtin.lineinfile:
        path: /opt/webitel/.bootstrap
        line: webitel_core
        insertbefore: BOF
