---
- when: inventory_hostname in groups['webitel_core']
  block:
    - include: install.yml
      become: true
      tags:
        - webitel_core_install

    - include: configure.yml
      become: true
      tags:
        - webitel_core_configure