---
- when: inventory_hostname in groups['webitel_core']
  block:
    - ansible.builtin.include_tasks: install.yml
      tags:
        - webitel_core_install

    - ansible.builtin.include_tasks: configure.yml
      tags:
        - webitel_core_configure
