---
- name: Install rabbitmq-server package
  ansible.builtin.apt:
    name: rabbitmq-server
    update_cache: false

- name: Get rabbitmq version
  ansible.builtin.command: rabbitmqctl version
  register: rabbitmq_version
