---
- when: inventory_hostname in groups['rabbitmq']
  block:
    - include_tasks: install.yml
      tags:
        - rabbitmq_install

    - include_tasks: configure.yml
      tags:
        - rabbitmq_configure