---
- when: inventory_hostname in groups['rabbitmq']
  block:
    - ansible.builtin.include_tasks: install.yml
      tags:
        - rabbitmq_install

    - ansible.builtin.include_tasks: configure.yml
      tags:
        - rabbitmq_configure
