---
- when: groups['all'] | length > 1
  block:
    - name: Configure DBs to listen on ip address
      postgresql_set:
        name: listen_addresses
        value: "localhost,{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
      become_user: postgres

    - name: Enable other Webitel hosts to login
      blockinfile:
        path: /etc/postgresql/14/main/pg_hba.conf
        marker: "# {mark} ANSIBLE MANAGED BLOCK - hosts"
        block: |
          {% for host in groups['all'] %}
          host    all     all     {{ hostvars[host]['ansible_default_ipv4']['address'] }}/32    scram-sha-256
          {% endfor %}

- name: Set max_connections value
  postgresql_set:
    name: max_connections
    value: "150"
  become_user: postgres