---
- name: Install PostgreSQL 15 and timescaledb packages
  ansible.builtin.apt:
    name:
      - postgresql-15
      - webitel-postgresql-15
      - timescaledb-2-postgresql-15
    update_cache: false
  when: inventory_hostname in groups['postgresql']

- name: Execute timescaledb-tune
  ansible.builtin.command: timescaledb-tune --quiet --yes
  when: inventory_hostname in groups['postgresql_main']

- name: Enable PostgreSQL at startup (systemd)
  ansible.builtin.systemd:
    name: postgresql
    enabled: true
    daemon_reload: true
    state: restarted
  when:
    - ansible_service_mgr == "systemd"
