---
- when: inventory_hostname in groups['postgresql']
  block:
    - include: install.yml
      become: true
      tags:
        - postgresql_install

    - include: configure.yml
      become: true
      tags:
        - postgresql_configure