---
- when: inventory_hostname in groups['postgresql']
  block:
    - include_tasks: install.yml
      tags:
        - postgresql_install

    - include_tasks: configure.yml
      tags:
        - postgresql_configure