---
- when: inventory_hostname in groups['postgresql']
  block:
    - ansible.builtin.include_tasks: install.yml
      tags:
        - postgresql_install

    - ansible.builtin.include_tasks: configure.yml
      tags:
        - postgresql_configure
