---
- name: Update repositories cache and install fail2ban packages
  ansible.builtin.apt:
    pkg:
      - rsyslog
      - fail2ban
    state: latest
    install_recommends: false
    update_cache: true

- name: Change loglevel
  ansible.builtin.replace:
    path: /etc/opensips/opensips.cfg
    regexp: (LOG_LOCAL0)$
    replace: LOG_LOCAL7
  notify: restart opensips

- name: Change /etc/rsyslog.conf file
  ansible.builtin.lineinfile:
    path: /etc/rsyslog.conf
    line: local7.* /var/log/opensips.log
  notify: restart rsyslog

- name: Change jail.conf file
  ansible.builtin.blockinfile:
    path: /etc/fail2ban/jail.conf
    block: |
      [opensips]
      enabled  = true
      filter   = opensips
      action   = iptables-allports[name=opensips, protocol=all]
      logpath  = /var/log/opensips.log
      maxretry = 5
      bantime = 3600

- name: Create /var/log/opensips.log file
  ansible.builtin.file:
    dest: /var/log/opensips.log
    state: touch
  notify:
    - restart logrotate
    - restart opensips

- name: Add Fail2Ban config
  ansible.builtin.template:
    src: files/fail2ban_opensips.conf
    dest: /etc/fail2ban/filter.d/opensips.conf
  notify:
    - restart logrotate
    - restart fail2ban

- name: Add logrotate config
  ansible.builtin.template:
    src: files/logrotate_opensips.conf
    dest: /etc/logrotate.d/opensips
  notify:
    - restart logrotate

- name: Enable Fail2Ban at startup (systemd)
  ansible.builtin.systemd:
    name: fail2ban
    enabled: true
  when:
    - ansible_service_mgr == "systemd"
