---
- name: Install OpenSIPS packages
  ansible.builtin.apt:
    name:
      - opensips
      - opensips-http-modules
      - opensips-postgres-module
      - opensips-presence-modules
      - opensips-rabbitmq-modules
      - opensips-wss-module
      - opensips-tls-module
      - opensips-tlsmgm-module
      - opensips-xmlrpc-module
    state: latest
    install_recommends: false
    update_cache: false

- name: Enable OpenSIPS at startup (systemd)
  ansible.builtin.systemd:
    name: opensips
    enabled: true
  when:
    - ansible_service_mgr == "systemd"
