---
- when: inventory_hostname in groups['opensips']
  block:
    - include_tasks: install.yml
      tags:
        - opensips_install

    - include_tasks: configure.yml
      tags:
        - opensips_configure

    - include_tasks: fail2ban.yml
      tags:
        - opensips_fail2ban
      when: opensips_fail2ban | bool