---
- when: inventory_hostname in groups['webitel_storage']
  block:
    - ansible.builtin.include_tasks: install.yml
      tags:
        - webitel_storage_install

    - ansible.builtin.include_tasks: configure.yml
      tags:
        - webitel_storage_configure

    - name: Fetch the pre-signed cert from storage to master
      run_once: true
      ansible.builtin.fetch:
        src: /opt/storage/key.pem
        dest: buffer/
        flat: "true"
        cmd: ""
      tags:
        - webitel_flow_manager_configure
