---
- when: inventory_hostname in groups['webitel_storage']
  block:
    - include: install.yml
      become: true
      tags:
        - webitel_storage_install

    - include: configure.yml
      become: true
      tags:
        - webitel_storage_configure

    - name: Fetch the pre-signed cert from storage to master
      run_once: yes
      fetch: src=/opt/storage/key.pem dest=buffer/ flat=yes
      tags:
        - webitel_flow_manager_configure