---
- when: groups['postgresql'] | length > 1
  block:
    - name: Enable replication user to login
      blockinfile:
        path: /etc/postgresql/15/main/pg_hba.conf
        marker: "# {mark} ANSIBLE MANAGED BLOCK - replication"
        block: |
          {% for host in groups['postgresql'] %}
          host    replication     wbtrepl     {{ hostvars[host]['ansible_default_ipv4']['address'] }}/32    scram-sha-256
          {% endfor %}

- name: Reload systemd
  systemd:
    name: "postgresql.service"
    enabled: yes
    daemon_reload: true
    state: restarted