---
- when: groups['postgresql'] | length > 1
  block:
    - name: Create "replication" user, set password, grant privs
      postgresql_user:
        name: wbtrepl
        password: password
        role_attr_flags: REPLICATION
      become_user: postgres

- name: Create "opensips" user, set password, grant privs
  postgresql_user:
    name: opensips
    password: webitel
    role_attr_flags: SUPERUSER
  become_user: postgres

- name: Create a new database with name "webitel"
  postgresql_db:
    name: webitel
    owner: opensips
  register: create_db
  become_user: postgres

- name: Restore database "webitel" from the file
  postgresql_db:
    name: webitel
    owner: opensips
    state: restore
    target: "{{ item }}"
  with_items:
    - /usr/share/postgresql/15/webitel/webitel-db-schema.sql
    - /usr/share/postgresql/15/webitel/webitel-db-data.sql
  become_user: postgres
  when: create_db is changed
