---
- when: groups['postgresql'] | length > 1
  block:
    - name: Create "replication" user, set password, grant privs
      postgresql_user:
        name: wbtrepl
        password: password
        role_attr_flags: REPLICATION
      become_user: postgres

- name: Create "opensips" user, set password, grant privs
  postgresql_user:
    name: opensips
    password: webitel
    role_attr_flags: SUPERUSER
  become_user: postgres

- name: Create a new database with name "webitel"
  postgresql_db:
    name: webitel
    owner: opensips
  register: create_db
  become_user: postgres

- name: Download database schema
  ansible.builtin.get_url:
    url: https://git.webitel.com/projects/WEP/repos/postgres/raw/{{ item }}?at=refs%2Ftags%2F{{ webitel_version }}
    dest: /tmp/{{ item }}
    mode: "0777"
  become_user: postgres
  with_items:
    - webitel-db-schema.sql
    - webitel-db-data.sql
  when:
    - create_db is changed
    - webitel_version != 'dev'

- name: Download DEV database schema
  ansible.builtin.get_url:
    url: https://git.webitel.com/projects/WEP/repos/postgres/raw/{{ item }}
    dest: /tmp/{{ item }}
    mode: "0777"
  become_user: postgres
  with_items:
    - webitel-db-schema.sql
    - webitel-db-data.sql
  when:
    - create_db is changed
    - webitel_version == 'dev'

- name: Restore database "webitel" from the file
  postgresql_db:
    name: webitel
    owner: opensips
    state: restore
    target: "{{ item }}"
  with_items:
    - /tmp/webitel-db-schema.sql
    - /tmp/webitel-db-data.sql
  become_user: postgres
  when: create_db is changed

- name: Delete downloaded files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /tmp/webitel-db-schema.sql
    - /tmp/webitel-db-data.sql
  when: create_db is changed
