---
- when: inventory_hostname in groups['postgresql_main']
  block:
    - ansible.builtin.include_tasks: configure.yml
      tags:
        - postgresql_configure

    - ansible.builtin.include_tasks: databases.yml
      tags:
        - postgresql_databases

    - ansible.builtin.include_tasks: cron.yml
      tags:
        - postgresql_cron
