---
- when: "'postgresql_standby' in groups"
  block:
    - when: inventory_hostname in (groups['postgresql_standby'] | default([]))
      block:
        - ansible.builtin.include_tasks: configure.yml
          tags:
            - postgresql_standby_configure
