---
- when: inventory_hostname in groups['webitel_flow_manager']
  block:
    - ansible.builtin.include_tasks: install.yml
      tags:
        - webitel_flow_manager_install

    - ansible.builtin.include_tasks: configure.yml
      tags:
        - webitel_flow_manager_configure
