---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  listen: restart systemd

- name: Restart logrotate
  ansible.builtin.service:
    name: logrotate
    state: restarted

- name: Restart rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted

- name: Restart opensips
  ansible.builtin.service:
    name: opensips
    state: restarted

- name: Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted
