---
- name: Restart opensips
  ansible.builtin.systemd_service:
    name: opensips
    state: restarted
    daemon_reload: true
  listen: restart opensips

- name: Restart rsyslog
  ansible.builtin.systemd_service:
    name: rsyslog
    state: restarted
  listen: restart rsyslog

- name: Restart fail2ban
  ansible.builtin.systemd_service:
    name: fail2ban
    state: restarted
  listen: restart fail2ban
