- name: Change site name
  replace:
    path: /etc/nginx/sites-enabled/default
    after: 'server_name '
    before: ';'
    regexp: '^(.+)$'
    replace: '{{ nginx_site_name }}'

- name: Create and Install Cert
  command: "certbot --nginx -d  {{ nginx_site_name }} -m {{ nginx_mail_address }} --agree-tos --noninteractive --redirect"

- name: Set Letsencrypt Cronjob for Certificate Auto Renewal
  cron:
    name: letsencrypt_renewal
    special_time: monthly
    job: "/usr/bin/certbot renew"

- name: Restart nginx
  systemd:
    name: "nginx.service"
    daemon_reload: true
    state: restarted
  when:
    - ansible_service_mgr == "systemd"