---
- when: inventory_hostname in groups['nginx']
  block:
    - include: install.yml
      become: true
      tags:
        - certbot_install

    - include: configure.yml
      become: true
      tags:
        - certbot_configure
