---
- when: inventory_hostname in groups['nginx']
  block:
    - include_tasks: install.yml
      tags:
        - certbot_install

    - include_tasks: configure.yml
      tags:
        - certbot_configure
