{
 "title": "Agent",
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "agent_id",
    "label": "Agent",
    "query": "select coalesce(u.name, u.username)  AS __text, a.id AS __value from call_center.cc_agent a inner join directory.wbt_user u on u.id = a.user_id  where dc= $domain_id  limit 1000"
   },
   { "name": "domain_id", "query": "${VAR_DOMAIN_ID}" },
   {
    "name": "agent",
    "query": "select coalesce(u.name, u.username) as name\n/*       u.extension,\n       u.dnd,\n       t.name as team_name,\n       aud.names as auditors,\n       sup.names as supervisors,\n       a.progressive_count,\n       a.chat_count */\nfrom call_center.cc_agent a\n    inner join directory.wbt_user u on u.id = a.user_id\n    left join call_center.cc_team t on t.id = a.team_id\n    left join lateral (\n        select string_agg(coalesce(aud.name, aud.username), ',') as names\n        from directory.wbt_user aud\n        where aud.id = any(a.auditor_ids)\n\n    ) aud on true\n    left join lateral (\n        select string_agg(aud.\"user\"->>'name', ',') as names\n        from call_center.cc_agent_with_user aud\n        where aud.id = any(a.supervisor_ids)\n    ) sup on true\nwhere a.domain_id = $domain_id and a.id = $agent_id"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"text-align: center;\">          \n  <span style=\"font-size: xx-large;\">${agent} </span>\n</div>"
   },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Breaks for today",
   "type": "table",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 2 },
   "targets": [
    {
     "rawSql": "select c.name \"Cause\",\n       ((extract(epoch from\n           case when a.status = 'pause' and a.status_payload = c.name then\n           now() - a.last_state_change + coalesce(tp.duration, interval '0')\n           else coalesce(tp.duration, interval '0') end) / 60)::double precision / limit_min) * 100 \"Time\"\nfrom call_center.cc_pause_cause c\n         inner join  call_center.cc_agent a on a.id = $agent_id\n         left join call_center.cc_agent_today_pause_cause tp on tp.cause = c.name and tp.id = a.id\nwhere c.domain_id = 1 and a.domain_id = c.domain_id\norder by c.name"
    }
   ]
  },
  {
   "title": "Calls",
   "type": "table",
   "gridPos": { "h": 21, "w": 13, "x": 11, "y": 2 },
   "targets": [
    {
     "rawSql": "select ch.created_at \"Time\",\n       ch.direction \"Direction\",\n       ch.destination \"Number\",\n       q.name \"Queue\",\n       extract(epoch  from ch.hangup_at - ch.created_at)::int8 \"Duration\",\n       ch.cause \"Hangup cause\"\nfrom call_center.cc_calls_history ch\n    left join call_center.cc_queue q on q.id = ch.queue_id\nwhere ch.domain_id = $domain_id\n  and ch.user_id = (select user_id from call_center.cc_agent a where a.id = $agent_id)\n  and ch.created_at between $__timeFrom() and $__timeTo()\norder by ch.created_at desc\nlimit 200;"
    }
   ]
  },
  {
   "title": "Status log",
   "type": "table",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "select ac.state \"Status\",\n       ac.joined_at \"Sign in\",\n       ac.joined_at + ac.duration \"Sign out\",\n       extract(epoch from ac.duration) \"Duration\"\nfrom call_center.cc_agent_state_history ac\nwhere ac.agent_id = $agent_id\n    and joined_at between $__timeFrom() and $__timeTo()\norder by ac.joined_at desc\nlimit 5000"
    }
   ]
  }
 ]
}