{
 "title": "IVR queue",
 "tags": [ "dash" ],
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   { "name": "domain_id", "query": "${VAR_DOMAIN_ID}" },
   {
    "name": "q",
    "label": "Queues",
    "query": "select name __text, id __value\nfrom call_center.cc_queue q\nwhere q.domain_id = $domain_id and q.type = 2"
   }
  ]
 },
 "panels": [
  {
   "title": "Resources",
   "type": "table",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select r.name \"Name\",\n       coalesce(a.cnt, 0) \"Used\",\n       r.\"limit\" \"Limit\",\n       coalesce((a.cnt * 100) / r.\"limit\", 0) \"Used %\"\nfrom call_center.cc_outbound_resource r\n    left join (\n        select a.resource_id, count(*) cnt\n        from call_center.cc_member_attempt a\n        where a.resource_id notnull and a.state != 'leaving'\n        group by 1\n    ) a on a.resource_id = r.id\nwhere r.domain_id = $domain_id and r.enabled\n    and r.id in (\n    select distinct oi.resource_id\n    from call_center.cc_queue_resource qr\n        inner join call_center.cc_outbound_resource_group og on og.id = qr.resource_group_id\n        inner join call_center.cc_outbound_resource_in_group oi on oi.group_id = og.id\n    where qr.queue_id in ($q)\n    )\norder by 4 desc, 1;"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n    count(*) \"Calls\",\n    (select count(*) from call_center.cc_member_attempt aa where aa.queue_id in ($q) and aa.state != 'leaving') \"In work\",\n    count(*) filter ( where ch.answered_at notnull and (ch.amd_result = 'HUMAN' or ch.amd_result isnull )) \"Answered\",\n    count(*) filter ( where t.parent_id notnull) \"Transfers\",\n    extract(epoch from avg(ch.answered_at - ch.created_at) filter ( where ch.answered_at notnull )) \"Avg response time\",\n    extract(epoch from avg(ch.hangup_at - ch.created_at) filter ( where ch.answered_at notnull )) \"Average duration\"\n    /*count(*) filter (where ch.payload->>'Promise' = 'SMS') \"SMS\",\n    count(*) filter (where ch.payload->>'Promise' = 'PromiseToday22') \"Today 22\",\n    count(*) filter (where ch.payload->>'Promise' = 'PromiseTomorrow16') \"Tomorrow 16\",\n    count(*) filter (where ch.payload->>'Promise' = 'PromiseDayAfterTomorrow16') \"DayAfterTomorrow 16\"*/\nfrom call_center.cc_member_attempt_history a\n    left join call_center.cc_calls_history ch on ch.id = a.member_call_id::varchar\n    left join call_center.cc_member_attempt_history t on t.parent_id = a.id\nwhere  a.domain_id = $domain_id\n  and a.joined_at between $__timeFrom()::timestamptz and $__timeTo()::timestamptz\n  and a.queue_id in ($q)"
    }
   ]
  },
  {
   "title": "Active calls",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "select a.joined_at \"Time\",\n       a.destination->>'destination' as \"Number\",\n       c.state \"State\",\n       case when tq.name notnull then mq.name || ' > ' || tq.name else mq.name end \"Queue\",\n       c.answered_at \"Answered\",\n       extract(epoch from now() - a.joined_at) \"Duration\",\n       r.name \"Resource\",\n       u.user->>'name' \"Agent\"\nfrom call_center.cc_member_attempt a\n    left join call_center.cc_outbound_resource r  on r.id = a.resource_id\n    left join call_center.cc_calls c on c.id = a.member_call_id\n    left join call_center.cc_member_attempt t on t.parent_id = a.id\n    left join call_center.cc_agent_with_user u on u.id = t.agent_id\n    left join call_center.cc_queue mq on mq.id = a.queue_id\n    left join call_center.cc_queue tq on tq.id = t.queue_id\nwhere a.state != 'leaving' and a.queue_id in ($q)\norder by c.answered_at desc nulls last ;"
    }
   ]
  },
  {
   "title": "Transfers to the queues",
   "type": "table",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "select\n    case when lag(q.name) over (order by q.priority, t.agent_id nulls first) = q.name then '' else q.name end \"Queue\",\n    coalesce(u.\"user\"->>'name', '') \"Agent\",\n    case when t.agent_id isnull then sum(t.c) over (partition by q.name) else t.c end as \"Answered\",\n    case when t.agent_id isnull then sum(t.cnt) over (partition by q.name)  end \"Transfer to the queue\",\n    t.aht_o \"Avg processing time\",\n    t.asa_o \"Avg response time\"\nfrom (\n    select h.queue_id,\n       hp.agent_id,\n       count(*) ccc,\n       count(*) filter ( where hp.bridged_at notnull ) c,\n       count(*) filter ( where hp.parent_id notnull ) cnt,\n       avg(extract(epoch from hp.bridged_at - hp.offering_at)) filter ( where hp.bridged_at notnull ) asa_o,\n       avg(extract(epoch from coalesce(hp.reporting_at, hp.leaving_at) - hp.bridged_at)) filter ( where hp.bridged_at notnull ) aht_o\n    from call_center.cc_member_attempt_history h\n        left join call_center.cc_member_attempt_history hp on hp.parent_id = h.id\n    where (h.domain_id = $domain_id::int8\n               and h.joined_at between $__timeFrom()::timestamptz and $__timeTo()::timestamptz \n               and h.queue_id in ($q)\n        )\n    group by 1, 2\n) t\n    inner join call_center.cc_queue q on q.id = t.queue_id\n    left join call_center.cc_agent_with_user u on u.id = t.agent_id\norder by q.priority, t.agent_id nulls first\n;"
    }
   ]
  },
  {
   "title": "Hangup cause",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 15 },
   "targets": [
    {
     "rawSql": "select now() as time, t.value, t.metric\nfrom (\n         select count(*) as metric, ch.cause || ' (' || ch.sip_code || ')' as value\n         from call_center.cc_member_attempt_history a\n                  inner join call_center.cc_calls_history ch on ch.id = a.member_call_id\n         where a.domain_id = $domain_id\n           and a.joined_at between $__timeFrom()::timestamptz\n           and $__timeTo()::timestamptz\n           and a.queue_id in ($q)\n         group by 2\n     ) t\n     where t.metric notnull;"
    }
   ]
  },
  {
   "title": "Queue calls",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select\n    public.time_bucket('$__interval', a.joined_at::timestamptz) as time,\n    q.name as metric,\n    count(*) as value\nfrom call_center.cc_member_attempt_history a\n    left join call_center.cc_queue q on q.id = a.queue_id\nwhere a.domain_id = $domain_id\n    and a.joined_at between $__timeFrom()::timestamptz and $__timeTo()::timestamptz \n    and a.queue_id in($q)\ngroup by 1, 2\norder by 1, 2;"
    }
   ]
  },
  {
   "title": "Information",
   "type": "table",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 24 },
   "targets": [
    {
     "rawSql": "select q.name \"Queue\",\n       a.cnt \"In work\",\n       coalesce(sum(qs.member_waiting), 0) \"Pending\",\n       coalesce(sum(qs.member_count), 0) as \"Total\",\n       case when coalesce(sum(qs.member_count - qs.member_waiting)) > 0\n           then  (coalesce(sum(qs.member_count - qs.member_waiting), 0)::double precision / coalesce(sum(qs.member_count), 0)::double precision) * 100\n           else 100.0 end \"Progress\"\nfrom call_center.cc_queue q\n    left join call_center.cc_queue_statistics qs on qs.queue_id = q.id\n    left join call_center.cc_bucket b on b.id = qs.bucket_id\n    left join lateral (\n        select count(*) cnt\n        from call_center.cc_member_attempt a\n        where a.queue_id = q.id and a.state != 'leaving'\n    ) a on true\nwhere q.domain_id = $domain_id and q.id in ($q)\ngroup by 1,2, q.priority\norder by q.priority desc;"
    }
   ]
  }
 ]
}