{
 "title": "Progressive dialing",
 "tags": [ "dash" ],
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   { "name": "domain_id", "query": "${VAR_DOMAIN_ID}" },
   {
    "name": "q",
    "label": "Queues",
    "query": "select name __text, id __value\nfrom call_center.cc_queue q\nwhere q.domain_id = $domain_id and q.type = 4"
   }
  ]
 },
 "panels": [
  {
   "title": "Agents",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select\n    u.\"user\"->>'name' \"Agent\",\n    case a.status \n      when 'online'  then 1\n      when 'offline'  then 2\n      when 'pause'  then 3\n      else 4 end\n    as \"Status\",\n    t.notbr_cnt \"Member did not answer\",\n    t.member_answer \"Member answered\",\n    t.br_cnt \"Connected with agent\",\n    t.missed \"Missed\",\n    t.aht \"AHT\",\n    t.asa \"Agent's ASA\",\n    t.asa_m \"Member's ASA\"\nfrom (\n         select a.agent_id,\n                count(*) filter ( where a.bridged_at notnull )                                                  br_cnt,\n                count(*) filter ( where a.bridged_at isnull )                                                   notbr_cnt,\n                count(*) filter ( where mc.answered_at notnull and (mc.amd_result::text = 'HUMAN'::text OR mc.amd_result::text = 'NOTSURE'::text or mc.amd_result IS NULL) ) member_answer,\n                avg(extract(epoch from (coalesce(a.reporting_at, a.leaving_at) - a.bridged_at)))\n                filter ( where a.bridged_at notnull )                                                           aht,\n                count(*) filter ( where ac.id notnull and ac.bridged_at isnull )                               missed,\n                avg(extract(epoch from ac.answered_at - ac.created_at)) filter ( where ac.answered_at notnull ) asa,\n                avg(extract(epoch from mc.answered_at - mc.created_at)) filter ( where mc.answered_at notnull ) asa_m\n         from call_center.cc_member_attempt_history a\n                  left join call_center.cc_calls_history ac on ac.domain_id = $domain_id and ac.id = a.agent_call_id\n                  left join call_center.cc_calls_history mc on mc.domain_id = $domain_id and mc.id = a.member_call_id\n         where a.domain_id = $domain_id\n           and a.joined_at between $__timeFrom()::timestamptz and $__timeTo()::timestamptz \n           and a.queue_id in ($q)\n         group by 1\n     ) t\n    inner join call_center.cc_agent_with_user u on u.id = t.agent_id\n    left join call_center.cc_agent a on a.id = t.agent_id;"
    }
   ]
  },
  {
   "title": "Active calls",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "select a.joined_at \"Время\",\n       a.destination->>'destination' as \"Number\",\n       a.state \"State\",\n       c.answered_at \"Answered\",\n       u.\"user\"->>'name' \"Agent\",\n       case when a.bridged_at notnull\n            then extract(epoch from coalesce(a.leaving_at, now()) - a.bridged_at)::int8\n            else 0 end \"Agent in a call\",\n       extract(epoch from now() - a.joined_at)::int8 \"Duration\",\n       r.name \"Resource\"\nfrom call_center.cc_member_attempt a\n    left join call_center.cc_outbound_resource r  on r.id = a.resource_id\n    left join call_center.cc_calls c on c.id = a.member_call_id\n    left join call_center.cc_agent_with_user u on u.id = a.agent_id\nwhere a.state != 'leaving' and a.queue_id in ($q)\norder by a.answered_at desc nulls last ;"
    }
   ]
  },
  {
   "title": "Queue calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "select\n    public.time_bucket('$__interval', a.joined_at::timestamptz) as time,\n    q.name as metric,\n    count(*) as value\nfrom call_center.cc_member_attempt_history a\n    left join call_center.cc_queue q on q.id = a.queue_id\nwhere a.domain_id = $domain_id\n    and a.joined_at between $__timeFrom()::timestamptz and $__timeTo()::timestamptz \n    and a.queue_id in($q)\ngroup by 1, 2\norder by 1, 2;"
    }
   ]
  },
  {
   "title": "Hangup causes",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 17 },
   "targets": [
    {
     "rawSql": "select now() as time, count(*) as metric, ch.cause || ' (' || ch.sip_code || ')' as value\nfrom call_center.cc_calls_history ch\nwhere ch.domain_id = $domain_id\n  and ch.created_at between $__timeFrom()::timestamptz and $__timeTo()::timestamptz \n  and ch.queue_id in ($q)\ngroup by 1, 3;"
    }
   ]
  },
  {
   "title": "Information",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "select q.name \"Queue\",\n       a.cnt \"In work\",\n       coalesce(sum(qs.member_waiting), 0) \"Waiting\",\n       coalesce(sum(qs.member_count), 0) as \"Total\",\n       case when coalesce(sum(qs.member_count - qs.member_waiting)) > 0\n           then  (coalesce(sum(qs.member_count - qs.member_waiting), 0)::double precision / coalesce(sum(qs.member_count), 0)::double precision) * 100\n           else 100.0 end \"Progress\"\nfrom call_center.cc_queue q\n    left join call_center.cc_queue_statistics qs on qs.queue_id = q.id\n    left join call_center.cc_bucket b on b.id = qs.bucket_id\n    left join lateral (\n        select count(*) cnt\n        from call_center.cc_member_attempt a\n        where a.queue_id = q.id and a.state != 'leaving'\n    ) a on true\nwhere q.domain_id = $domain_id and q.id in ($q)\ngroup by 1,2, q.priority\norder by q.priority desc;"
    }
   ]
  }
 ]
}