---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  listen: restart systemd

- name: Restart grafana
  become: true
  ansible.builtin.service:
    name: grafana-server
    state: restarted
  tags:
    - grafana_run

- name: Set privileges on provisioned dashboards
  become: true
  ansible.builtin.file:
    path: /var/lib/grafana/dashboards
    recurse: true
    owner: grafana
    group: grafana
    mode: "0640"
  listen: provisioned dashboards changed

- name: Set privileges on provisioned dashboards directory
  become: true
  ansible.builtin.file:
    path: /var/lib/grafana/dashboards
    state: directory
    recurse: false
    mode: "0755"
  listen: provisioned dashboards changed
