---
- name: Generate locales
  community.general.locale_gen:
    name: "{{ item }}"
    state: present
  loop: "{{ base_locales }}"

- name: Apply sysctl values
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_set: true
    state: present
    reload: true
  loop: "{{ base_sysctl | dict2items }}"
