---
- when: inventory_hostname in groups['freeswitch']
  block:
    - include_tasks: install.yml
      tags:
        - freeswitch_install

    - include_tasks: configure.yml
      tags:
        - freeswitch_configure