---
- when: inventory_hostname in groups['freeswitch']
  block:
    - ansible.builtin.include_tasks: install.yml
      tags:
        - freeswitch_install

    - ansible.builtin.include_tasks: configure.yml
      tags:
        - freeswitch_configure
