---
- when: inventory_hostname in groups['webitel_call_center']
  block:
    - ansible.builtin.include_tasks: install.yml
      tags:
        - webitel_call_center_install

    - ansible.builtin.include_tasks: configure.yml
      tags:
        - webitel_call_center_configure
