---
- name: Install NGINX and webitel frontend applications
  apt:
    name:
      - nginx
      - webitel-auth-app
      - webitel-admin-app
      - webitel-agent-workspace
      - webitel-supervisor-workspace
      - webitel-flow-diagram
      - webitel-history
      - webitel-audit-app
      - webitel-web-widget
    update_cache: no