---
- name: Install NGINX and Webitel frontend applications
  ansible.builtin.apt:
    name:
      - nginx
    update_cache: false

- name: Install Webitel frontend applications
  ansible.builtin.apt:
    name:
      - webitel-auth-app
      - webitel-admin-app
      - webitel-agent-workspace
      - webitel-supervisor-workspace
      - webitel-flow-diagram
      - webitel-history
      - webitel-audit-app
      - webitel-web-widget
      - webitel-crm
    update_cache: false