---
- when: inventory_hostname in groups['nginx']
  block:
    - include_tasks: install.yml
      tags:
        - nginx_install

    - include_tasks: configure.yml
      tags:
        - nginx_configure

    - include_role:
        name: nginx/certbot
      tags:
        - nginx_letsencrypt
      when: nginx_letsencrypt | bool